BEGIN;

-- Import des fichiers games_*.csv
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_0_1991.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_1992.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_1993.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_1994.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_1995.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_1996.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_1997.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_1998.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_1999.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2000.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2011.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2012.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2013.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2014.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2015.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2016.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2017.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2018.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2019.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2020.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2021.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2022.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2023.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_2024.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_KingBase.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN00.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN01.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN02.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN03.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN04.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN05.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN06.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN07.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN08.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN09.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN10.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN11.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN12.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN13.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN14.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN15.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN16.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN17.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN18.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_PGN19.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_collections.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_openings1.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_openings2.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_players1.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_players2.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic1997.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic1998.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic1999.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic2000.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic2001.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic2002.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic2003.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic2004.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic2005.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic2006.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic2007.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic2008.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic2009.csv' WITH (FORMAT csv, HEADER true);
\COPY games (file_name, game_index, event, site, date, round, white, black, result, eco, moves) FROM '/data/games_twic2010.csv' WITH (FORMAT csv, HEADER true);

-- Import des fichiers position_games_*.csv
\COPY tmp_position_games FROM '/data/position_games_0_1991.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_1992.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_1993.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_1994.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_1995.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_1996.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_1997.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_1998.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_1999.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2000.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2011.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2012.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2013.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2014.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2015.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2016.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2017.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2018.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2019.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2020.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2021.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2022.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2023.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_2024.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_KingBase.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN00.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN01.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN02.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN03.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN04.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN05.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN06.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN07.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN08.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN09.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN10.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN11.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN12.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN13.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN14.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN15.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN16.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN17.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN18.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_PGN19.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_collections.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_openings1.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_openings2.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_players1.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_players2.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic1997.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic1998.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic1999.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic2000.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic2001.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic2002.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic2003.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic2004.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic2005.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic2006.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic2007.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic2008.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic2009.csv' WITH (FORMAT csv, HEADER true);
\COPY tmp_position_games FROM '/data/position_games_twic2010.csv' WITH (FORMAT csv, HEADER true);

COMMIT;